// Mocks generated by Mockito 5.4.4 from annotations
// in intellicook_mobile/test/widgets/high_level/profile_account_panel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async';

import 'package:app_controller_client/app_controller_client.dart';
import 'package:intellicook_mobile/providers/app_controller/me.dart';
import 'package:mockito/mockito.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

class MockMe extends AutoDisposeAsyncNotifier<UserGetResponseModel>
    with Mock
    implements Me {
  UserGetResponseModel? buildReturn;

  @override
  Future<UserGetResponseModel> build() async => buildReturn!;
}
