// Mocks generated by Mockito 5.4.4 from annotations
// in intellicook_mobile/test/widgets/high_level/ingredient_chip_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;

import 'ingredient_chip_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IngredientChipCallbacks].
///
/// See the documentation for Mockito's code generation for more information.
class MockIngredientChipCallbacks extends _i1.Mock
    implements _i2.IngredientChipCallbacks {
  @override
  void onEdit(String? ingredient) => super.noSuchMethod(
        Invocation.method(
          #onEdit,
          [ingredient],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onRemove() => super.noSuchMethod(
        Invocation.method(
          #onRemove,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
