#!/bin/sh

cd "$(git rev-parse --git-dir)/.." || exit

echo "Checking formatting..."

if dart format --set-exit-if-changed --output none lib test ; then
  echo "Formatting is OK."
else
  echo "Formatting is NOT OK. Please fix the formatting or run \`flutter format\`, then try again."
  exit 1
fi

echo "Checking analysis..."

if flutter analyze; then
  echo "Analysis is OK."
else
  echo "Analysis is NOT OK. Please fix the issues or run \`dart fix --apply\`, then try again."
  exit 1
fi

exit 0
